Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/trusty64"
  config.vm.hostname = "mininet"
  config.vm.provision "shell", inline: $mininet_setup
  config.vm.synced_folder ".", "/vagrant", create: true

end



$mininet_setup = <<SCRIPT
  # Install mininet
  sudo apt-get install -y mininet
  sudo service openvswitch-controller stop
  sudo update-rc.d openvswitch-controller disable
  sudo apt-get install -y git
  git clone https://github.com/mininet/mininet.git
  mininet/util/install.sh

  # Enable ECN
  sudo sysctl -w net.ipv4.tcp_ecn=1

  # Enable NewReno congestion control algorithm
  sudo sysctl -w net.ipv4.tcp_congestion_control=reno
SCRIPT